services:
  db:
    image: postgres:16.1
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 13579
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: