changeLogFile=src/main/resources/db/changelog/db.changelog-master.yml
db.url=jdbc:postgresql://localhost:5432/postgres
db.user=dev
db.password=13579
#db.name=postgres
db.driver=org.postgresql.Driver
sessionStorageTime=60
api.key=a6653c018f1af73946bbea12556fd32a