changeLogFile=src/main/resources/db/changelog/db.changelog-master.yml
db.url=jdbc:postgresql://localhost:5432/postgres
db.user=dev
db.password=${DB_PASSWORD}
#db.name=postgres
db.driver=org.postgresql.Driver
sessionStorageTime=60
api.key=${API_KEY}
url.city=http://api.openweathermap.org/data/2.5/weather
url.geo=http://api.openweathermap.org/geo/1.0/direct